# Generated by Django 4.1.5 on 2023-01-23 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="AdressModel",
            new_name="AddressModel",
        ),
        migrations.RemoveField(
            model_name="profilemodel",
            name="imege",
        ),
        migrations.AddField(
            model_name="profilemodel",
            name="image",
            field=models.ImageField(
                default="default/user.jpg", upload_to="accont/profile/image"
            ),
        ),
    ]
