# Generated by Django 4.1.5 on 2023-02-05 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0002_rename_adressmodel_addressmodel_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profilemodel",
            name="image",
            field=models.ImageField(
                default="default/user.jpg", upload_to="accounts/profile/image/"
            ),
        ),
    ]
