# Generated by Django 4.1.5 on 2023-01-10 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_unitmodel_categorymodel_productmodel_category_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="categorymodel",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.categorymodel",
            ),
        ),
        migrations.AlterField(
            model_name="unitmodel",
            name="baise",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.unitmodel",
            ),
        ),
    ]
