# Generated by Django 4.1.5 on 2023-01-10 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_categorymodel_parent_alter_unitmodel_baise"),
    ]

    operations = [
        migrations.RenameField(
            model_name="productmodel",
            old_name="Category",
            new_name="category",
        ),
        migrations.RenameField(
            model_name="productmodel",
            old_name="Unit",
            new_name="unit",
        ),
        migrations.AddField(
            model_name="unitmodel",
            name="conversion_rate",
            field=models.FloatField(default=1.0),
        ),
    ]
