# Generated by Django 4.1.5 on 2023-01-16 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_cartmodel_cartitemmodel"),
    ]

    operations = [
        migrations.RenameField(
            model_name="unitmodel",
            old_name="baise",
            new_name="base",
        ),
    ]
