# Generated by Django 4.1.5 on 2023-01-16 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_rename_baise_unitmodel_base"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductImageModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("status", models.BooleanField(default=True)),
                (
                    "path",
                    models.ImageField(
                        default="default/product.jpg", upload_to="product/image/"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.RemoveField(
            model_name="productmodel",
            name="image",
        ),
        migrations.AddField(
            model_name="productmodel",
            name="images",
            field=models.ManyToManyField(to="core.productimagemodel"),
        ),
    ]
