# Generated by Django 4.1.5 on 2023-02-08 11:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0011_ordermodel_paymentmodel_reviewmodel_wishlistmodel"),
    ]

    operations = [
        migrations.AddField(
            model_name="ordermodel",
            name="cart",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.cartmodel",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="ordermodel",
            name="is_delivered",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="ordermodel",
            name="is_paid",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="ordermodel",
            name="order_id",
            field=models.CharField(default="1", max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="paymentmodel",
            name="is_captured",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="paymentmodel",
            name="is_success",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="paymentmodel",
            name="order",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.ordermodel",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="paymentmodel",
            name="payment_id",
            field=models.CharField(default="1", max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="paymentmodel",
            name="payment_method",
            field=models.CharField(default="1", max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="paymentmodel",
            name="receipt_no",
            field=models.CharField(default="1", max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="reviewmodel",
            name="comment",
            field=models.TextField(default="no comments", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="reviewmodel",
            name="images",
            field=models.ManyToManyField(to="core.productimagemodel"),
        ),
        migrations.AddField(
            model_name="reviewmodel",
            name="product",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.productmodel",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="reviewmodel",
            name="rating",
            field=models.FloatField(default=5.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="reviewmodel",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="wishlistmodel",
            name="name",
            field=models.CharField(default="My Wishlist", max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="wishlistmodel",
            name="product",
            field=models.ManyToManyField(to="core.productmodel"),
        ),
        migrations.AddField(
            model_name="wishlistmodel",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
