# Generated by Django 4.1.5 on 2023-02-09 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_ordermodel_cart_ordermodel_is_delivered_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cartitemmodel",
            old_name="quantiti",
            new_name="quantity",
        ),
    ]
