# Generated by Django 4.1.5 on 2023-02-09 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_rename_quantiti_cartitemmodel_quantity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cartitemmodel",
            name="quantity",
            field=models.FloatField(default=1.0),
        ),
    ]
